apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  labels:
    app: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-pvc
  labels:
    app: llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
